### PR TITLE
Query maintenance

### PR DESCRIPTION
**Pull request by PLNech**
- Mark  `Query#setNumericFilters` as deprecated in favor of `setFilters`
- Add `@Nonnull`/`@Nullable`

### CODE REVIEW

**Comment by PLNech** [comment]
@clement-leprovost: I'm not sure which of the following syntax is best:

- 1:
```
public @Nullable foo()
```
- 2:
```
@Nullable
public foo()
```
- 3:
```
public 
@Nullable
foo()
```

(They are all valid according to the [Java 8 syntax](http://docs.oracle.com/javase/specs/jls/se8/html/jls-8.html#jls-MethodDeclaration).)

WDYT?

**Comment by ElPicador** [comment]
What I see more often is 2)
```
@Nullable
public foo()
```

My2cents

**Comment by clement-leprovost** [comment]
It seems that @ElPicador has spent too much time coding Scala... :p He is forgetting the return type! And the `@Nullable` annotation should be attached to that type. So I prefer:

```public @Nullable String foo()```

**Comment by clement-leprovost** [comment]
LGTM 👍

**Comment by ElPicador** [comment]
Only to ~troll~ debate: https://google.github.io/styleguide/javaguide.html#s4.8.5-annotations

**Pull request merged**
