### PR TITLE
fix(waitTask): Deprecate broken waitTask(int)

### PR DESCRIPTION
**Pull request by PLNech**
Deprecate waitTask(int) as taskIDs are not guaranteed to be integers:
> leo: They should always be _numeric values_, but I would guess they are 64bits values not 32bits values

@spinach: Do you think this is a case where we should introduce a "breaking" change? (If waitTask(int) will anyway error at runtime, should we remove it to trigger the error at compile time?)

### CODE REVIEW

**Comment by spinach** [comment]
@PLNech I am for moving the error from runtime to compile time, it's always better. If `waitTask(int)` has no use cases (as Leo hinted at), then I agree with you: we can introduce a breaking change.

**Comment by PLNech** [comment]
@spinach: agreed, I'll wait for @robertmogos's take before merging!

**Comment by PLNech** [comment]
@spinach / @robertmogos : no news is good news? Unless you ask for changes, I'll consider this is approved 😉

**Comment by robertmogos** [comment]
Sorry @spinach , I didn't realize I was a part of this review 👍

**Comment by PLNech** [comment]
@robertmogos Noprob! thanks 👍

**Pull request merged**
