### PR TITLE
Refactoring with HTTPUrlConnexion

### PR DESCRIPTION
**Pull request by PLNech**
Stop using the DefautHttpClient as [recommanded](http://developer.android.com/about/versions/marshmallow/android-6.0-changes.html#behavior-apache-http-client), fixing #24. 

@redox: LGTY?

### CODE REVIEW

**Comment by redox** [comment]
I think we definitely need to go that way @PLNech but it seems that right now this version is not providing any Keep-Alive capabilities because we're re-instantiating the `HttpURLConnection` at each request.

Do you know if there is some dark magic somewhere keeping the connection alive? Or maybe there is a way to recycle the `HttpURLConnection` to keep the connection opened?

**Comment by PLNech** [comment]
@redox: There is indeed [some dark magic](https://stackoverflow.com/questions/3304006/persistent-httpurlconnection-in-java) in [java](https://docs.oracle.com/javase/6/docs/technotes/guides/net/http-keepalive.html) that pools HttpURLConnections, which works on Android too *as long as you close the underlying InputStream*.

However, there may be [a bug with gzipped content](https://code.google.com/p/android/issues/detail?id=43132) that prevents connection reuse [until Android 4.4](https://code.google.com/p/android/issues/detail?id=38817#c14).  I'll investigate and if it is an issue, we can always switch to [OkHttp](https://square.github.io/okhttp/)!

**Comment by clement-leprovost-algolia** [comment]
Yeah, I stumbled upon the gzipped content bug like on my second day with Android! It happens when `Content-Encoding: gzip` but `Content-Length: 0`, which basically happens if you are doing a conditional GET (like `If-Modified-Since` or `If-None-Match`) and the server replies a `304 Not Modified`. So we *should not* hit it, although I'm really not comfortable with using a bugged library... :/

I have used OkHttp for a personal project, and found it was good.

**Comment by PLNech** [comment]
Thanks for the details, I guess we're safe from this issue for now. Apart from this `HttpURLConnection` does not seem to have any other known bug that could affect us, but I agree there is no reason to keep using it just for the sake of it being in the standard library.  And besides the stability enhancement, OkHttp has better performance, has HTTP/2 support and a few other advantages. But we may consider the benefits of using it with a high-level wrapper such as [Retrofit](http://square.github.io/retrofit/) or [Volley](https://developer.android.com/training/volley/index.html) before using it.

To fix #24 at the soonest, once I'll confirm Keep-Alive is functional I think we can merge this and release a new minor version. I'll open a ticket for the OkHttp migration as an enhancement!

**Comment by redox** [comment]
Works for me :+1: I'll let you guys merge+release/tag+publish

**Comment by clement-leprovost-algolia** [comment]
Yes, this PR should definitely be merged. @PLNech Just gimme a sign if you need help on this.

However, I think we need to talk before using OkHttp. I'm not in favor of it (even if it's a good library) and even less in the favor of higher-level libraries like Retrofit or Volley. Remember that we are providing an SDK here, not writing a custom app. So, in my opinion, the less dependencies we have, the better for our users.

**Comment by PLNech** [comment]
@clement-leprovost-algolia: Thanks, as I am WFH I would be glad to let you handle the publishing. I'll notify you when I'm done testing and merging this!

Indeed, that is something we need to talk about. Let's discuss this before any other refactoring!

**Comment by dethi** [comment]
I share the same opinion about dependencies as @clement-leprovost-algolia. That's why the Swift API Client has no dependency.

**Comment by PLNech** [comment]
After manual testing, Keep-Alive seems to work correctly.

@dethi: Good point. I'm merging this and won't create any ticket regarding OkHttp, as for now it does not seem to have enough benefits to be worth introducing a dependency.

**Pull request merged**
