### PR TITLE
V2.0.0

### LINKED ISSUE #4: gradle dependency / jcenter or maven central
Hey,
Would it be possible for you to upload releases?
It is way convinient to use from gradle or maven based android projects.
Cheers!

### LINKED ISSUE #9: SNI fixes/support
Check http://blog.dev001.net/post/67082904181/android-using-sni-and-tlsv1-2-with-apache

### LINKED ISSUE #10: Task specific interfaces
Any chance of splitting the [IndexListener](https://github.com/algolia/algoliasearch-client-android/blob/master/src/main/java/com/algolia/search/saas/IndexListener.java) in several smaller interfaces?

This one has too many methods. Let's say we just want to use the search bit of Algolia, why would I have to implement ?
```@Override
    public void addObjectsResult(Index index, JSONArray jsonArray, JSONObject jsonObject) {

    }
```

### LINKED ISSUE #11: Respond Client request using onPostExecute
if you move this [_sendRequest](https://github.com/algolia/algoliasearch-client-android/blob/master/src/main/java/com/algolia/search/saas/APIClient.java#L411) call to the onPostExecute method from the AsyncTask, the results will be received on the Main Application Thread and so we can safely update the UI as need.

### PR DESCRIPTION
**Pull request by dethi**
* Rewrite all the API, so I think it's only 60% backward compatible (methods signature are the same, but the listener changed a lot) :disappointed: 
* Travis unit testing on Android emulator :smiley: 
* Jcenter, close #4 
* Fix #11 
* Fix #10 
* Check SNI supports (seems to work), close #9 

To generate a new release for JCenter:

* Update the version in **BaseAPIClient.java** and **build.gradle**
* Build the release and upload it to JCenter

```bash
./gradlew clean build generateRelease
```

TODO:

* [x] Check code
* [X] Update documentation
* [x] Add optional listener
* [x] Publish on JCenter
* [ ] Explain somewhere that the listener are all optional (you can pass `null`)
* [ ] Update the installation instruction : android-algoliasearch --> algoliasearch-android

### CODE REVIEW

**Comment by redox** [comment]
Currently waiting for our Sonatype repository: https://issues.sonatype.org/browse/OSSRH-17250

**Comment by dethi** [comment]
Cool :)

**Comment by dethi** [comment]
Haha you got the same problem as me with javadoc :)

**Comment by redox** [comment]
> Haha you got the same problem as me with javadoc :)

Yep, should be OK now :)

**Comment by redox** [comment]
So we're on MavenCentral: http://search.maven.org/#search%7Cga%7C1%7Calgoliasearch :+1:

**Comment by dethi** [comment]
Maybe we should merge it or put a message in the README about this new release because if a new developer want to try the API Client, he will use the old one and nobody will never try this one. And we know that the old one doesn't work correctly...

**Comment by redox** [comment]
Yes, I just need to update our website to use the new API.

**Comment by dethi** [comment]
Oh yes! You're right.
PS: I love the new team's name :smile:

**Comment by kamoljan** [comment]
Thank you!

**Comment by redox** [comment]
@kamoljan we're about to merge that PR to master; all working fine for you? Do you grab the package from Maven Central?

**Comment by kamoljan** [comment]
@redox Maven Central didn't work for me.
I am downloading jar files manualy right now :(

**Comment by dethi** [comment]
@kamoljan Did you tried with `com.algolia:algoliasearch-android:2.+` ? There is an error in the documentation, it's **not** `com.algolia:android-algoliasearch:2.+`

**Comment by kamoljan** [comment]
@dethi, sorry I didn't try it yet. Decided to use RESTFul API instead of the Android SDK.

**Pull request merged**
